/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
        
/**
 *
 * @author Romilson dos Santos
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
         //Faz o formulário iniciar no centro da tela
        this.setLocationRelativeTo(null);
        // Insere título na tela
        this.setTitle("Cálculo Horas");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Módulos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 51))); // NOI18N

        jCheckBox1.setText("VHS Front");

        jCheckBox2.setText("VHS Financeiro");

        jCheckBox3.setText("VHS Almoxarifado");

        jCheckBox4.setText("VHS PDV");

        jCheckBox5.setText("VHS Telefonia");

        jCheckBox6.setText("VHS Contabilidade");

        jCheckBox7.setText("Livros Fiscais");

        jCheckBox8.setText("CMNet Reservas");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOTVWEB", "VHF FULL", "VHS Special" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NFCE", "ECF" }));

        jCheckBox25.setText("NFSe");

        jCheckBox26.setText("Boleto bancário");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox25)
                        .addContainerGap(164, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox26)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCheckBox8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox8)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox7)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Implantação", "Treinamento" }));

        jLabel2.setText("Tipo");

        jButton1.setText("Gerar Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Local");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remoto", "Presencial" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Implantação", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VHS Financeiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 102))); // NOI18N

        jCheckBox11.setText("Cadastro");

        jCheckBox12.setText("Operacional");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCheckBox11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VHS Almoxarifado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 102))); // NOI18N

        jCheckBox13.setText("Cadastro");

        jCheckBox14.setText("Operacional");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox14))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VHS Front", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 102))); // NOI18N

        jCheckBox9.setText("Cadastro");

        jCheckBox10.setText("Operacional");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox10)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VHS Telefonia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 102))); // NOI18N

        jCheckBox17.setText("Cadastro");

        jCheckBox18.setText("Operacional");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VHS PDV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 102))); // NOI18N

        jCheckBox15.setText("Cadastro");

        jCheckBox16.setText("Operacional");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox16))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jCheckBox15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox16)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VHS Contabilidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 102))); // NOI18N

        jCheckBox19.setText("Cadastro");

        jCheckBox20.setText("Operacional");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox20))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jCheckBox19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Livros Fiscais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 102))); // NOI18N

        jCheckBox21.setText("Cadastro");

        jCheckBox22.setText("Operacional");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox21)
                    .addComponent(jCheckBox22))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckBox21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Treinamento", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Relatório Horas");

        jLabel4.setText("Criado por Romilson dos Santos");

        jLabel5.setText("Versão: 20170925");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // Fecha a aplicação
        System.exit(0);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      try {   
        // Cálculo das horas
        
        // Verifica se uma das opções do campo módulos está selecionado
        if (jCheckBox1.isSelected() == false && jCheckBox2.isSelected() == false && jCheckBox3.isSelected() == false && jCheckBox4.isSelected() == false && jCheckBox5.isSelected() == false && jCheckBox6.isSelected() == false && jCheckBox7.isSelected() == false && jCheckBox8.isSelected() == false && jCheckBox25.isSelected() == false && jCheckBox26.isSelected() == false){
          
           // Exibe tela informando que não há opções selecionadas no campo Módulos
           JOptionPane.showMessageDialog(null,"Favor selecionar umas das opções do campo Módulos!");
           // Interrompe a execução das instruções abaixo
           return;           
            
        }
        
        // Verifica se o campo CMNet Reservas está selecionado com outro módulo
        if ((jCheckBox1.isSelected() || jCheckBox2.isSelected() || jCheckBox3.isSelected() || jCheckBox4.isSelected() || jCheckBox5.isSelected() || jCheckBox6.isSelected() || jCheckBox7.isSelected() || jCheckBox25.isSelected() || jCheckBox26.isSelected()) && (jCheckBox8.isSelected())){
          
           // Exibe tela informando que não se pode selecionar CMNet Reservas e outros módulos ao mesmo tempo.
           JOptionPane.showMessageDialog(null,"Favor não selecionar o módulo CMNet Reservas com outros módulos!");
           // Interrompe a execução das instruções abaixo
           return;           
            
        }

        // Zera a variável TotalHoras
        Classes.Remoto.setTotalHoras(0);
        // Zera a variável TotalHorasCad
        Classes.Remoto.setTotalHorasCad(0);
        // Zera a variável TotalHorasOper
        Classes.Remoto.setTotalHorasOper(0);

        String escolha = "";
             
        // Campo VHS Front
        if(jCheckBox1.isSelected()){
            // Campo Cadastro
            if (jCheckBox9.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){
                    
                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getFrontCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Remoto.getFrontCad());

                }
                else if (jComboBox2.getSelectedItem().equals("Presencial")){
                    
                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getFrontCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Presencial.getFrontCad());

                }

            }
            // Campo Operacional
            if (jCheckBox10.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){
                    
                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getFrontOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Remoto.getFrontOper());
                    
                }
                else if (jComboBox2.getSelectedItem().equals("Presencial")){
                    
                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getFrontOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Presencial.getFrontOper());

                }
            }
        }

        // Campo VHS Financeiro
        if(jCheckBox2.isSelected()){
            // Campo Cadastro
            if (jCheckBox11.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getFinanCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Remoto.getFinanCad());
                    
                }
                else if (jComboBox2.getSelectedItem().equals("Presencial")){
                    
                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getFinanCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Presencial.getFinanCad());

                }

            }
            // Campo Operacional
            if (jCheckBox12.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getFinanOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Remoto.getFinanOper());

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getFinanOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Presencial.getFinanOper());

                }

            }
        }

        // Campo VHS Almoxarifado
        if(jCheckBox3.isSelected()){
            // Campo Cadastro
            if (jCheckBox13.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getAlmoxCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Remoto.getAlmoxCad());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getAlmoxCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Presencial.getAlmoxCad());

                }

            }
            // Campo Operacional
            if (jCheckBox14.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getAlmoxOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Remoto.getAlmoxOper());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getAlmoxOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Presencial.getAlmoxOper());

                }

            }
        }

        // Campo VHS PDV
        if(jCheckBox4.isSelected()){
            // Campo Cadastro
            if (jCheckBox15.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getPDVCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Remoto.getPDVCad());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getPDVCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Presencial.getPDVCad());

                }

            }
            // Campo Operacional
            if (jCheckBox16.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getPDVOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Remoto.getPDVOper());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getPDVOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Presencial.getPDVOper());

                }

            }
             // Implantação NFCe
             if (jComboBox4.getSelectedItem().equals("NFCE")){

                Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getTotalNFCe());

             }

        }

        // Campo VHS Telefonia
        if(jCheckBox5.isSelected()){
            // Campo Cadastro
            if (jCheckBox17.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getTelefCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Remoto.getTelefCad());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getTelefCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Presencial.getTelefCad());

                }

            }
            // Campo Operacional
            if (jCheckBox18.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getTelefOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Remoto.getTelefOper());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getTelefOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Presencial.getTelefOper());

                }

            }
        }

        // Campo VHS Contabilidade
        if(jCheckBox6.isSelected()){
            // Campo Cadastro
            if (jCheckBox19.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getContabCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Remoto.getContabCad());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getContabCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Presencial.getContabCad());

                }

            }
            // Campo Operacional
            if (jCheckBox20.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getContabOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Remoto.getContabOper());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getContabOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Presencial.getContabOper());

                }

            }
        }

        // Campo Livros Fiscais
        if(jCheckBox7.isSelected()){
            // Campo Cadastro
            if (jCheckBox21.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getFiscalCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Remoto.getFiscalCad());

                }else if (jComboBox2.getSelectedItem().equals("Presencial")){
                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getFiscalCad());
                    Classes.Remoto.setTotalHorasCad(Classes.Remoto.getTotalHorasCad() + Classes.Presencial.getFiscalCad());

                }

            }
            // Campo Operacional
            if (jCheckBox22.isSelected()){

                if (jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getFiscalOper());
                    Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Remoto.getFiscalOper());

                }

            }else if (jComboBox2.getSelectedItem().equals("Presencial")){

                Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getFiscalOper());
                Classes.Remoto.setTotalHorasOper(Classes.Remoto.getTotalHorasOper() + Classes.Presencial.getFiscalOper());

            }

        }

        // Campo CMNet Reservas
        if(jCheckBox8.isSelected()){

            escolha = jComboBox3.getSelectedItem().toString();
            switch(escolha){

                case "HOTVWEB" :
                Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Reservas.getReserva());
                break;

                case "VHF FULL" :
                Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Reservas.getReservaFull());
                break;

                case "VHS Special" :
                Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Reservas.getReservaSpecial());
                break;

            }

        }

        // NFSe
        if(jCheckBox25.isSelected()){

            Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getTotalNFSe());

        }

        //Boleto bancário
        if(jCheckBox26.isSelected()){

            Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getTotalBoleto());

        }

        // Estações
        if(jComboBox1.getSelectedItem().equals("Implantação") && jCheckBox8.isSelected() == false){

            Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getTotalEstacao());

        }
        
        // Acompanhamento de cadastros
        if(jComboBox2.getSelectedItem().equals("Remoto")){

            Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getTotalHorasAcompCad());

        }else if(jComboBox2.getSelectedItem().equals("Presencial")){
            
            Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getTotalHorasAcompCad());
            
        }
        
        // Acompanhamento operacional
        if(jComboBox2.getSelectedItem().equals("Remoto")){
            
         Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Remoto.getTotalHorasAcompOper());
         
        }else if(jComboBox2.getSelectedItem().equals("Presencial")){
            
            Classes.Remoto.setTotalHoras(Classes.Remoto.getTotalHoras() + Classes.Presencial.getTotalHorasAcompOper());
            
        }
        
        // Criação do relatório
        Classes.Relatorios.setRelatorio("Cálculo Total de Horas: \n");
        
        if(jCheckBox8.isSelected()){            
            
            switch(escolha){

                case "HOTVWEB" :
                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTotal de horas do projeto: " + Classes.Reservas.getReserva() + " Horas\n");
                break;

                case "VHF FULL" :
                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTotal de horas do projeto: " + Classes.Reservas.getReservaFull() + " Horas\n");
                break;

                case "VHS Special" :
                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTotal de horas do projeto: " + Classes.Reservas.getReservaSpecial() + " Horas\n");
                break;

            }
              
            
            
        }else{
            
           Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTotal de horas do projeto: " + Classes.Remoto.getTotalHoras() + " Horas\n");
        
        }
        
        if(jCheckBox8.isSelected() == false){  
           // Acompanhamento de cadastros
           if(jComboBox2.getSelectedItem().equals("Presencial")){

              Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTotal de horas acompanhamento de cadastros: " + Classes.Presencial.getTotalHorasAcompCad() + " Horas\n");

           }else if(jComboBox2.getSelectedItem().equals("Remoto")){
            
              Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTotal de horas acompanhamento de cadastros: " + Classes.Remoto.getTotalHorasAcompCad() + " Horas\n");;
            
           }
        
           // Acompanhamento operacional
           if(jComboBox2.getSelectedItem().equals("Presencial")){

              Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTotal de horas acompanhamento operacional: " + Classes.Presencial.getTotalHorasAcompOper() + " Horas\n");

           }else if(jComboBox2.getSelectedItem().equals("Remoto")){
            
              Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTotal de horas acompanhamento operacional: " + Classes.Remoto.getTotalHorasAcompOper() + " Horas\n");;
            
           }
        }
        
        
        // Estações
        if (jComboBox1.getSelectedItem().equals("Implantação") && jCheckBox8.isSelected() == false){

            Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nTotal de horas instalação e configuração nas máquinas: " + Classes.Remoto.getTotalEstacao()+ " Horas");

        }

        if (jCheckBox4.isSelected() && jComboBox4.getSelectedItem().equals("NFCE")){
            Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nTotal de horas instalação e configuração NFCe: " + Classes.Remoto.getTotalNFCe()+ " Horas");

        }

        // VHS Front
        if (jCheckBox1.isSelected()){
            if(jCheckBox9.isSelected() || jCheckBox10.isSelected()){

                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nVHS Front:");

            }
            //Cadastro
            if(jCheckBox9.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                  Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Front: " + Classes.Remoto.getFrontCad() + " Horas");
                
                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                  Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Front: " + Classes.Presencial.getFrontCad() + " Horas");
                    
                }                  
                    
            }
            //Operacional
            if(jCheckBox10.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Front: " + Classes.Remoto.getFrontOper()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Front: " + Classes.Presencial.getFrontOper()+ " Horas"); 
                    
                }
                
            }
            
        }

        // VHS Financeiro
        if (jCheckBox2.isSelected()){
            if(jCheckBox11.isSelected() || jCheckBox12.isSelected()){

                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nVHS Financeiro:");

            }
            //Cadastro
            if(jCheckBox11.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){
                    
                  Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Financeiro: " + Classes.Remoto.getFinanCad()+ " Horas");
           
                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                  Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Financeiro: " + Classes.Presencial.getFinanCad()+ " Horas");  
                
                }
                
            }
            
            //Operacional
            if(jCheckBox12.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Financeiro: " + Classes.Remoto.getFinanOper()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Financeiro: " + Classes.Presencial.getFinanOper()+ " Horas");
                   
                }
                
            }
        }

        // VHS Almoxarifado
        if (jCheckBox3.isSelected()){
            if(jCheckBox13.isSelected() || jCheckBox14.isSelected()){

                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nVHS Almoxarifado:");

            }
            //Cadastro
            if(jCheckBox13.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Almoxarifado: " + Classes.Remoto.getAlmoxCad()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Almoxarifado: " + Classes.Presencial.getAlmoxCad()+ " Horas");
                    
                }
                
            }
            //Operacional
            if(jCheckBox14.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Almoxarifado: " + Classes.Remoto.getAlmoxOper()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Almoxarifado: " + Classes.Presencial.getAlmoxOper()+ " Horas");
                    
                }
            }
        }

        // VHS PDV
        if (jCheckBox4.isSelected()){
            if(jCheckBox15.isSelected() || jCheckBox16.isSelected()){

                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nVHS PDV:");

            }
            //Cadastro
            if(jCheckBox15.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS PDV: " + Classes.Remoto.getPDVCad()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS PDV: " + Classes.Presencial.getPDVCad()+ " Horas");
                    
                }
                
            }
            //Operacional
            if(jCheckBox16.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS PDV: " + Classes.Remoto.getPDVOper()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){  
                
                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS PDV: " + Classes.Presencial.getPDVOper()+ " Horas");
                }
            }
        }

        // VHS Telefonia
        if (jCheckBox5.isSelected()){
            if(jCheckBox17.isSelected() || jCheckBox18.isSelected()){

                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nVHS Telefonia:");

            }
            //Cadastro
            if(jCheckBox17.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Telefonia: " + Classes.Remoto.getTelefCad()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Telefonia: " + Classes.Presencial.getTelefCad()+ " Horas"); 
                    
                }
                
            }
            //Operacional
            if(jCheckBox18.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Telefonia: " + Classes.Remoto.getTelefOper()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Telefonia: " + Classes.Presencial.getTelefOper()+ " Horas");
                    
                }
                               
            }
            
        }

        // VHS Contabilidade
        if (jCheckBox6.isSelected()){
            if(jCheckBox19.isSelected() || jCheckBox20.isSelected()){

                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nVHS Contabilidade:");

            }
            //Cadastro
            if(jCheckBox19.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Contabilidade: " + Classes.Remoto.getContabCad()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros VHS Contabilidade: " + Classes.Presencial.getContabCad()+ " Horas"); 
                    
                }
                
                
            }
            
            //Operacional
            if(jCheckBox20.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                     Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Contabilidade: " + Classes.Remoto.getContabOper()+ " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional VHS Contabilidade: " + Classes.Presencial.getContabOper()+ " Horas");
                    
                }                
                
            }
            
        }

        // Livros Fiscais
        if (jCheckBox7.isSelected()){
            if(jCheckBox21.isSelected() || jCheckBox22.isSelected()){

                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nLivros Fiscais:");

            }
            //Cadastro
            if(jCheckBox21.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros Livros Fiscais: " + Classes.Remoto.getFiscalCad() + " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                    Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação de cadastros Livros Fiscais: " + Classes.Presencial.getFiscalCad() + " Horas");
                    
                }
                
            }
            //Operacional
            if(jCheckBox22.isSelected()) {
                
                if(jComboBox2.getSelectedItem().equals("Remoto")){

                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional Livros Fiscais: " + Classes.Remoto.getFiscalOper() + " Horas");

                }else if(jComboBox2.getSelectedItem().equals("Presencial")){
                    
                   Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nCapacitação operacional Livros Fiscais: " + Classes.Presencial.getFiscalOper() + " Horas"); 
                    
                }                           
                
            }
            
        }

        // CMNet Reservas
        if (jCheckBox8.isSelected()){

            Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nCMNet Reservas:");

            switch(escolha){

                case "HOTVWEB" :
                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTreinamento: " + Classes.Reservas.getReserva() + " Horas");
                break;

                case "VHF FULL" :
                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTreinamento: " + Classes.Reservas.getReservaFull()+ " Horas");
                break;

                case "VHS Special" :
                Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\nTreinamento: " + Classes.Reservas.getReservaSpecial() + " Horas");
                break;

            }
        }

        // NFSe
        if (jCheckBox25.isSelected()){

            Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nNFSe implantação: " + Classes.Remoto.getTotalNFSe() + " Horas");

        }

        // Boleto bancário
        if (jCheckBox26.isSelected()){

            Classes.Relatorios.setRelatorio(Classes.Relatorios.getRelatorio() + "\n\nBoleto bancário implantação: " + Classes.Remoto.getTotalBoleto()+ " Horas");

        }

        // Abre a tela de Relatório
        this.dispose();
        Object args = null;
        TelaRelatorio.main((String[]) args);

      } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
